### ISSUE TITLE
babel-node

### ISSUE THREAD

**Issue by crobinson42** [developit/express-es6-rest-api#10]
I'm curious if you know something different, or if this is a just-for-fun repo, ;-)

> Not meant for production use
> You should not be using babel-node in production. It is unnecessarily heavy, with high memory usage due to the cache being stored in memory. You will also always experience a startup performance penalty as the entire app needs to be compiled on the fly.

https://babeljs.io/docs/usage/cli/

**Comment by developit** [comment]
@crobinson42 This repo is definitely designed for production use - `babel-node` is only used in development mode.  When you run this repo in production, the everything is pre-transpiled and run without `babel-node`, thus suitable for production usage.  You can see the difference below:

#### In _development_:

```sh
# live-reload and babel-node:
PORT=8080 npm run dev
```

#### In _production_:

```sh
# pre-transpile everything to dist:
npm run build

# run the pre-transpiled version:
PORT=8080 npm start
```

Let me know if that answers your question!

**Comment by crobinson42** [comment]
Ahh, very cool! I hadn't looked hard enough and didn't see the `build` script. I hope this is a repo/project you plan on expanding further!
