### ISSUE TITLE
Cannot find module babel-node

### ISSUE THREAD

**Issue by xeno** [developit/express-es6-rest-api#11]
While running the installation instructions, I first ran into an issue where ../lib/cli wasn't found. Globally installing "nodemon" solved that issue, but now I'm stuck on this one. I'd ask this in a chat but I don't see any other means of contacting you all for assistance. :)

`PORT=8080 npm run dev`

`> express-es6-rest-api@0.3.0 dev /Volumes/Xenophoto/Dropbox/src/[redacted]`
`> nodemon -w src --exec "babel-node src --presets es2015,stage-0"`

`[nodemon] 1.10.0`
`[nodemon] to restart at any time, enter 'rs'`
`[nodemon] watching: /Volumes/Xenophoto/Dropbox/src/[redacted]/src/**/*`
`[nodemon] starting 'babel-node src --presets es2015,stage-0'`
`module.js:440`
`    throw err;`
`    ^`
`Error: Cannot find module '../lib/babel-node'`
`    at Function.Module._resolveFilename (module.js:438:15)`
`    at Function.Module._load (module.js:386:25)`
`    at Module.require (module.js:466:17)`
`    at require (internal/module.js:20:19)`
`    at Object.<anonymous> (/Volumes/Xenophoto/Dropbox/src/[redacted]/node_modules/.bin/babel-node:3:1)`
`    at Module._compile (module.js:541:32)`
`    at Object.Module._extensions..js (module.js:550:10)`
`    at Module.load (module.js:456:32)`
`    at tryModuleLoad (module.js:415:12)`
`    at Function.Module._load (module.js:407:3)`
`[nodemon] app crashed - waiting for file changes before starting...`

**Comment by developit** [comment]
Hi there! 😊

Can you paste the output of `npm ls --depth 0`? 
Thanks!

**Comment by xeno** [comment]
I initially received an error with this, so I removed my node_modules and reinstalled, now i"m back to having the same error but with `../live/cli`

``npm ls --depth 0
express-es6-rest-api@0.3.0 /Volumes/Xenophoto/Dropbox/src/calypso
├── babel-cli@6.11.4
├── babel-core@6.13.2
├── babel-preset-es2015@6.13.2
├── babel-preset-stage-0@6.5.0
├── body-parser@1.15.2
├── compression@1.6.2
├── cors@2.7.1
├── eslint@3.3.1
├── express@4.14.0
├── nodemon@1.10.0
└── resource-router-middleware@0.5.1``

**Comment by developit** [comment]
hmm - what versions of node/npm are you using?  Seems very strange.

`npm -v && node -v`

**Comment by xeno** [comment]
3.10.5
v6.1.0

**Comment by developit** [comment]
interesting, same as me...

**Comment by developit** [comment]
Just did the full install process, and it works fine for me:

```sh
git clone git@github.com:developit/express-es6-rest-api.git tmp
cd tmp
npm i
PORT=8085 npm run dev
```

Are you using a custom registry or anything that could have messed up the installation?  Also make sure you're not setting `NPM_CONFIG_PRODUCTION=true` or `NODE_ENV=production` during installation.

**Comment by xeno** [comment]
How strange... I did your sequence of commands there (substituting the git URL for the http URL) and everything works fine now. Maybe there was an issue with my cloning download or something? Not sure, but it's working now. Thanks @developit Jason!

**Comment by developit** [comment]
Funky! Might have been a weird clone or something yeah. Glad it worked out 😊

**Comment by vijay1791** [comment]
deleted the node_modules and reinstalled it using "npm i" , It worked for me.

**Comment by savvymanuel** [comment]
> deleted the node_modules and reinstalled it using "npm i" , It worked for me.

WORKED FOR MEE TOO
