### ISSUE TITLE
Deletion doesn't work

### ISSUE THREAD

**Issue by vocalist** [developit/express-es6-rest-api#12]
The response of server to delete request to "url/id" is "500 (internal server error)"

**Comment by duard** [comment]
Error on delete here

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>ReferenceError: params is not defined
            <br> &nbsp; &nbsp;at _delete (/home/carlos/Desenvolvimento/api-duard/node_modules/restful-mongoose/src/index.js:37:28)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at next (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/route.js:137:13)
            <br> &nbsp; &nbsp;at Route.dispatch (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/route.js:112:3)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at /home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/index.js:281:22
            <br> &nbsp; &nbsp;at param (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/index.js:354:14)
            <br> &nbsp; &nbsp;at param (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/index.js:365:14)
            <br> &nbsp; &nbsp;at Function.process_params (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/index.js:410:3)
            <br> &nbsp; &nbsp;at next (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/index.js:275:10)
            <br> &nbsp; &nbsp;at Function.handle (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/index.js:174:3)
            <br> &nbsp; &nbsp;at router (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/index.js:47:12)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at trim_prefix (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/index.js:317:13)
            <br> &nbsp; &nbsp;at /home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/index.js:284:7
            <br> &nbsp; &nbsp;at Function.process_params (/home/carlos/Desenvolvimento/api-duard/node_modules/express/lib/router/index.js:335:12)
        </pre>
    </body>
</html>

**Comment by duard** [comment]
I changed the delete method to

```
		delete({ params }, res) {
			model.findByIdAndRemove(params[name], toRes(res));
		}

```
now it works
