### ISSUE TITLE
Any Suggestion for docker deployment ?

### ISSUE THREAD

**Issue by akashshinde** [developit/express-es6-rest-api#18]

**Comment by zouhir** [comment]
`Dockerfile` has to be placed in the your node service root dir

example one:

```
# Alpine linux is my goto for Node.js micro services
FROM alpine:3.4

# Update
RUN apk add --update nodejs bash git

# Create www folder to contain your Nodejs service code
# Then install app dependencies
COPY package.json /www/package.json
RUN cd /www; npm install

# Copy your code to our project folder
COPY . /www

WORKDIR /www

# If you need some env variable
ENV NODE_ENV production

# As per README you need port
ENV PORT 8080

# Expose the port to outside world
EXPOSE  8080

# RUN
CMD ["npm", start"]
```

I haven't tested it, but it theory it should work as a simple Node Docker image file.
If you have have any issues please reach out to me on here and I'll make sure I write you a tested working Docker example.

**Comment by developit** [comment]
Want to add that to the repo @zouhir? I added you as a collaborator.

**Comment by zouhir** [comment]
Yes! I'd love to if you like to have it 😃 I'll do that tonight after work

**Comment by zouhir** [comment]
Our API boilerplate is now dockerized! Please check the repo/readme.
