### ISSUE TITLE
Suggestions for dependent resources?

### ISSUE THREAD

**Issue by lionel-lints** [developit/express-es6-rest-api#19]
I forked this and began a small app using postgres and knex, and I am trying to understand the best way to implement dependent resources, any thoughts? (For example I am trying to set up user's todos, and I can't seem to get the resource-router-middleware to do what I want).

My fork is here: [flow_todos_api](https://github.com/lionel-lints/flow_todos_api).

Any thoughts appreciated, thanks!

**Comment by developit** [comment]
I'd recommend keeping all your resource top-level (not `/users/todos/`). For linking those resource to a user, unusually list the linkages on the user response. Via something like Mongoose you can use Virtual for this.

**Comment by lionel-lints** [comment]
Hey, thanks! Interesting, I was thinking about using restful routing, but I hear you here. OK so quick follow up, what do you mean by `unusually list linkages on the user response`? Do you mean that the response object will handle the structuring of the returned data? I'm a bit trying to think about when I want to just get the data for a user's posts (or todos, or whatever) how do I structure that call to the db? I obviously don't need all the todos from the db passed over to express for other users, if I were to not handle that by way of routing, what do you think might be the best way to approach that? Anyway, thanks so much for the quick follow up, it may be that resource-router is best paired with a noSQL type structure, and that is the source of the issue. But if you have any thoughts about it, please let me know.

Thanks again!

**Comment by developit** [comment]
I had meant something like this:

```
GET /user/1234
{
  "name": "jdoe",
  "todos": [
    { "id": "1", href:"/todos/1" },
    { "id": "2", href:"/todos/2" },
    { "id": "3", href:"/todos/3" },
    { "id": "4", href:"/todos/4" }
  ]
}
```

And then just resolving those on the client.  I've done this with Mongoose and you run into the issue you alluded to - a building relationships using a document-oriented database ends up causing a fairly large query overhead since you don't have access to joins or anything like that (something to resolve relationships within the DB).

**Comment by gxrneyme** [comment]
Why don't you store `todos` in each user's document in MongoDB, and add `href` at runtime, deriving the URL from the ID?

**Comment by developit** [comment]
@gxrneyme That's definitely the best way to go, and what I was trying to explain in my response (it was probably unclear, haha).  That lets you keep your resources independent but nicely link between them.  As a perk, if all resources have unique ID's and are located at the root, generating links is nice and simple:

```js
{ href: `/${resource.type}/${resource.id}` }
```

**Comment by lionel-lints** [comment]
Cool, thanks! I was trying to move the resources over into a relational DB,
but yeah I see what you are saying. Much appreciated! :-)
ᐧ

**Comment by gxrneyme** [comment]
@developit: Yeah, I agree. 

@lionel-lints: Even if you use a relational DB, you can always generate `links: [... whatever]` at run-time.
