### ISSUE TITLE
Async error

### ISSUE THREAD

**Issue by aviemet** [developit/express-es6-rest-api#26]
In `index.js`, the call to `app.server.listen()` is asynchronous, but a console output on the next line is expecting the process to have completed. It throws an error on my fresh install. I had to wrap the console output in the callback argument for `server.listen()`

```
app.server.listen(process.env.PORT || config.port, () => {
	console.log(`Started on port ${app.server.address().port}`);
});
```
instead of
```
app.server.listen(process.env.PORT || config.port);
console.log(`Started on port ${app.server.address().port}`);
```

**Comment by zouhir** [comment]
You are correct - it needs a callback.
 https://expressjs.com/en/4x/api.html#app.listen

will fix asap.

**Comment by zouhir** [comment]
This issue no longer exists! PR #30 fixed it!

Closing 🔥👍
