### ISSUE TITLE
Question about middleware

### ISSUE THREAD

**Issue by escobar5** [developit/express-es6-rest-api#39]
Hi, Can you give me an example of how to use a middleware, for example I have a route `'/users'` and I have a middleware to restrict access to that route, should I configure it in `'middleware/index.js'` ? how can I set that middleware only for that route?

Thanks

**Comment by developit** [comment]
Everything in this repo is a Router, and Routers can be mounted anywhere you want:

```
let middleware = someMiddleware();
router.use('/users', middleware);

// or if you're bypassing routers, install per-route:
app.get('/users', [
  someMiddleware(),
  (req, res, next) => {}
]);
```

**Comment by escobar5** [comment]
I get it, thank you!
