### ISSUE TITLE
How to set environment variables?

### ISSUE THREAD

**Issue by slorenzo** [developit/express-es6-rest-api#44]
Hi, I'm having troubles when I want to set environment variables.
I think that the best way is using diferent tasks on the `script` field in`package.json` to add this values but I don't know.

Do you know how I can create this task to get different values depends of the environment?

Thanks.

**Comment by developit** [comment]
```js
"scripts": {
  "start": "FOO=bar node ."
}
```

or:

```sh
FOO=bar npm start
```
