### ISSUE TITLE
how to change port?

### ISSUE THREAD

**Issue by Skyball** [developit/express-es6-rest-api#67]
# Start development live-reload server
PORT=8080 npm run dev

# Start production server:
PORT=8080 npm start

This does not work.

**Comment by pinceladasdaweb** [comment]
@Skyball 

Have you tried changing within the config.json file?

https://github.com/developit/express-es6-rest-api/blob/master/src/config.json

**Comment by Skyball** [comment]
> @Skyball
> 
> Have you tried changing within the config.json file?
> 
> https://github.com/developit/express-es6-rest-api/blob/master/src/config.json

this works for me.  

I also want to know how to configure multiple environments. Can you explain it to me？

**Comment by pinceladasdaweb** [comment]
@Skyball 

Follow these tutorials, they will help you:

https://medium.com/the-node-js-collection/making-your-node-js-work-everywhere-with-environment-variables-2da8cdf6e786
https://www.twilio.com/blog/2017/08/working-with-environment-variables-in-node-js.html
https://stackabuse.com/managing-environment-variables-in-node-js-with-dotenv/

**Comment by Skyball** [comment]
OK, thank you very much
